# Generated by Django 5.0.1 on 2024-05-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_banner',
            field=models.ImageField(default=1, upload_to='category_banner'),
            preserve_default=False,
        ),
    ]
