# Generated by Django 5.0.3 on 2024-07-21 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_category_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='CCI',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='price',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='time_begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='time_final',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
